name: Flutter CI

on:
  # Запуск вручную во вкладке Actions
  workflow_dispatch:
  # Автоматически при пуше в main ветку
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest # Используем Linux (быстро и бесплатно)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # Включаем кэш для ускорения [citation:4]

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
